#!/usr/bin/env zsh

setopt extended_glob

install() {
  local override target="$2/$(basename $1)"

  if [ -e "$target" ]; then
    vared -p "Override $target? [y|N] " override
    [[ "$override" =~ '[yY]' ]] || return 1
    printf 'rm -rf %s\n' "$target"
    rm -rf "$target"
  fi

  printf "ln -s %s %s\n" "$1" "$target"
  ln -s "$1" "$target"
}

install_all() {
  local p

  for p in $1/.*~$1/.git*; do
    install "$p" "$2"
  done
}

install_all "$(cd "$(dirname "$0")"; pwd)" "$HOME"
