#!/usr/bin/env zsh

# installs something
install() {
  [ -e "${2}" ] && return 1
  printf 'git clone %s %s\n' "${1}" "${2}"
  git clone "${1}" "${2}"
}

# installs a plugin
install_plugin() {
  install "${1}" "${2}/plugins/${${1##*/}%%.*}"
}

# uninstalls everything
remove() {
  printf 'rm -rf %s\n' "${1}"
  rm -rf "${1}"
}

# rbenv target dir
target=~/.rbenv

# rbenv git repo
repo='git://github.com/sstephenson/rbenv.git'

# rbenv plugins i need
plugins=(
  'git://github.com/sstephenson/ruby-build.git'
  'git://github.com/sstephenson/rbenv-gem-rehash.git'
  'git://github.com/chriseppstein/rbenv-each.git'
  'git://github.com/rkh/rbenv-update.git'
)

# Uninstall
if [ "${0##*/}" = 'uninstall-rbenv' ]; then
  remove "${target}"
  remove "${DOTROOT}/.zsh/local/rbenv.sh"
  exit 0
fi

# Install
install "${repo}" "${target}"

for plugin in $plugins; do
  install_plugin "${plugin}" "${target}"
done

cat > "${DOTROOT}/.zsh/local/rbenv.zsh" <<EOF
export PATH="\${HOME}/.rbenv/bin:\${PATH}"
eval "\$(rbenv init -)"
EOF
